### ISSUE TITLE
Results with indices

### ISSUE THREAD

**Issue by krebbi** [prprprus/PyMySQLPool#2]
Hi,

how do I get the query results with indices?

**Comment by krebbi** [comment]
PR with 3f1513c7a5333d7f51aae16af5a94f68b84f6cd7

**Comment by prprprus** [comment]
> Hi,
> 
> how do I get the query results with indices?

Hi.

Index are transparent to database drivers and connection pools. You can use SQL to create the index first, such as [MySQL](https://dev.mysql.com/doc/refman/5.7/en/create-index.html)(or useing ORM framework to create the index). Then you can query normally.

A simple example:

An index is created on the `name` field of the user table. Just need to execute
```SQL
SELECT $some_field FROM user WHERE name = $value;
```

**Comment by prprprus** [comment]
> PR with [3f1513c](https://github.com/prprprus/PyMySQLPool/commit/3f1513c7a5333d7f51aae16af5a94f68b84f6cd7)

Thank you so much. Merged.

**Comment by krebbi** [comment]
you're welcome.
