### ISSUE TITLE
resize_pool

### ISSUE THREAD

**Issue by BrainGithub** [prprprus/PyMySQLPool#5]
May I know the static rule, or the Mathematical basis of the resize_pool??
Really appreciate!

**Comment by BrainGithub** [comment]
I don't know the reason

**Comment by prprprus** [comment]
Hi, @BrainGithub

There is no esoteric mathematical principle. Just periodically count the ratio between unused list and usage list (count 3 times by default)
If exceed the threshold it means that there is too much idle connections then release of some.

I will add more comments and tidy up the code to make the code more readable.😃
