### ISSUE TITLE
MySQL Server has gone away

### ISSUE THREAD

**Issue by kawamanza** [prprprus/PyMySQLPool#8]
The pooled connection might to be idle for a long time, and the server may disconnect or kill the process for any reason. In this case, the broker should check the connection before deliver it to the requester. It would be nice if PyMySQLPool do a `ping()` after some amount of time to force reconnection.

**Comment by prprprus** [comment]
Hi, @kawamanza 

Thanks for your awesome advice, I think you are right, are you interested in submitting a pr 😏?

**Comment by kawamanza** [comment]
Hi @prprprus,

Great. I did a monkey-patch on a project that I am using your lib just to workaround this issue. I'll try to reply the code to a PR for your review.
